      SUBROUTINE MCMCSTEP(PAR,PROB,IFAIL) 

      IMPLICIT NONE 
 
      INTEGER M1FLAG,M2FLAG,M3FLAG,MHDFLAG,MHUFLAG
      INTEGER AKFLAG,ALFLAG,OMGFLAG,MAFLAG,IHIGGS,IGMU
      INTEGER NBIN,IFAIL,I,NTOT,IDUM
      INTEGER NSUSY,NGUT,NMES,NPROB
      PARAMETER (NSUSY=14,NGUT=21,NMES=15,NPROB=51)
 
      DOUBLE PRECISION PAR(*),PROB(*),P,RAN2,XDUM
      DOUBLE PRECISION SMASS(3),PMASS(2),CMASS,SCOMP(3,3),PCOMP(2,2)
      DOUBLE PRECISION MGL,MCHA(2),U(2,2),V(2,2),MNEU(5),NEU(5,5)
      DOUBLE PRECISION BRJJ(5),BRMM(5),BRLL(5),BRSS(5),BRCC(5)
      DOUBLE PRECISION BRBB(5),BRTT(5),BRWW(3),BRZZ(3),BRGG(5)
      DOUBLE PRECISION BRZG(5),BRHHH(4),BRHAA(3,3),BRHCHC(3)
      DOUBLE PRECISION BRHAZ(3,2),BRAHA(3),BRAHZ(2,3),BRHCW(5)
      DOUBLE PRECISION BRHIGGS(5),BRNEU(5,5,5),BRCHA(5,3)
      DOUBLE PRECISION BRHSQ(3,10),BRHSL(3,7),BRASQ(2,2),BRASL(2)
      DOUBLE PRECISION BRSUSY(5),WIDTH(5),OMG,OMGMIN,OMGMAX
      DOUBLE PRECISION HCBRM,HCBRL,HCBRSU,HCBRBU,HCBRSC,HCBRBC
      DOUBLE PRECISION HCBRBT,HCBRWH(5),HCBRWHT,HCBRNC(5,2)
      DOUBLE PRECISION HCBRSQ(5),HCBRSL(3),HCBRSUSY,HCWIDTH
      DOUBLE PRECISION CU(5),CD(5),CV(3),CJ(5),CG(5)
      DOUBLE PRECISION ALSMZ,ALEMMZ,GF,g1,g2,S2TW
      DOUBLE PRECISION MS,MC,MB,MBP,MT,MTAU,MMUON,MZ,MW
      DOUBLE PRECISION VUS,VCB,VUB,MHUS,MHDS,MSS
      DOUBLE PRECISION MUR,MUL,MDR,MDL,MLR,MLL,MNL
      DOUBLE PRECISION MST1,MST2,MSB1,MSB2,MSL1,MSL2,MSNT
      DOUBLE PRECISION CST,CSB,CSL,MSMU1,MSMU2,MSMUNT,CSMU,Q2
      DOUBLE PRECISION RMST1,RMST2,S2T,RMSB1,RMSB2,S2B,XT,XB
      DOUBLE PRECISION MGUT,g1s,g2s,g3s,HTOPS,HBOTS,HTAUS
      DOUBLE PRECISION G1GUT,G2GUT,G3GUT,LGUT,KGUT,HTOPGUT
      DOUBLE PRECISION HBOTGUT,HTAUGUT,M1GUT,M2GUT,M3GUT,ALGUT,AKGUT
      DOUBLE PRECISION ATGUT,ABGUT,ATAUGUT,AMUGUT,MHUGUT,MHDGUT,MSGUT
      DOUBLE PRECISION MQ3GUT,MU3GUT,MD3GUT,MQGUT,MUGUT,MDGUT,ML3GUT
      DOUBLE PRECISION ME3GUT,MLGUT,MEGUT,M0,M12,A0,SIGMU
      DOUBLE PRECISION M1INP,M2INP,M3INP,MHDINP,MHUINP,ALINP,AKINP
      DOUBLE PRECISION XIFINP,XISINP,MUPINP,MSPINP,MSINP,M3HINP
      DOUBLE PRECISION XIFGUT,XISGUT,MUPGUT,MSPGUT,M3HGUT
      DOUBLE PRECISION XIFSUSY,XISSUSY,MUPSUSY,MSPSUSY,M3HSUSY
      DOUBLE PRECISION Xf,sigmaV,xx(100),dNdx(100),EMIN
      DOUBLE PRECISION sigmaPiN,sigma0,csPsi,csNsi,csPsd,csNsd
      DOUBLE PRECISION MHUQ,MHDQ,MSQ,LQ,KQ,ALQ,AKQ,MUQ,NUQ
      DOUBLE PRECISION ZHU,ZHD,ZS,H1Q,H2Q,TANBQ,QSTSB
      DOUBLE PRECISION BRSG,BRSGmax,BRSGmin,DMd,DMdmin,DMdmax,DMs,
     . DMsmax,DMsmin,BRBMUMU,BRBMUMUmax,BRBMUMUmin,BRBtaunu,
     . BRBtaunumax,BRBtaunumin
      DOUBLE PRECISION delmagmu,damumin,damumax,amuthmax,amuthmin
      DOUBLE PRECISION brtopbw,brtopbh,brtopneutrstop(5,2),toptot
      DOUBLE PRECISION FTSUSY(NSUSY+2),FTGUT(NGUT+2),FTMES(NMES+2)
      DOUBLE PRECISION SIG(5,11),SIGT(5,6)
      DOUBLE PRECISION M0CEN,M12CEN,TBCEN,A0CEN,M1CEN,M2CEN
      DOUBLE PRECISION M3CEN,MHDCEN,MHUCEN,LCEN,ALCEN,AKCEN
      DOUBLE PRECISION KCEN,MUCEN,XCEN,XDEV,X,M0DEV,M12DEV
      DOUBLE PRECISION TBDEV,A0DEV,M1DEV,M2DEV,M3DEV,MHDDEV
      DOUBLE PRECISION MHUDEV,LDEV,ALDEV,AKDEV,KDEV,MUDEV
      DOUBLE PRECISION XMIN,XMAX,Y1MIN,Y2MIN

      COMMON/SIGMU/SIGMU
      COMMON/SOFTGUT/M0,M12,A0
      COMMON/INPPAR/M1INP,M2INP,M3INP,MHDINP,MHUINP,ALINP,AKINP,
     . XIFINP,XISINP,MUPINP,MSPINP,MSINP,M3HINP
      COMMON/BRN/BRJJ,BRMM,BRLL,BRSS,BRCC,BRBB,BRTT,BRWW,BRZZ,
     . BRGG,BRZG,BRHHH,BRHAA,BRHCHC,BRHAZ,BRAHA,BRAHZ,
     . BRHCW,BRHIGGS,BRNEU,BRCHA,BRHSQ,BRHSL,BRASQ,BRASL,
     . BRSUSY,WIDTH
      COMMON/BRC/HCBRM,HCBRL,HCBRSU,HCBRBU,HCBRSC,HCBRBC,
     . HCBRBT,HCBRWH,HCBRWHT,HCBRNC,HCBRSQ,HCBRSL,
     . HCBRSUSY,HCWIDTH
      COMMON/BRSG/BRSG,BRSGmax,BRSGmin,DMd,DMdmin,DMdmax,DMs,
     . DMsmax,DMsmin,BRBMUMU,BRBMUMUmax,BRBMUMUmin,BRBtaunu,
     . BRBtaunumax,BRBtaunumin
      COMMON/MAGMU/delmagmu,damumin,damumax,amuthmax,amuthmin
      COMMON/BR_top2body/brtopbw,brtopbh,brtopneutrstop
      COMMON/topwidth/toptot
      COMMON/REDCOUP/CU,CD,CV,CJ,CG
      COMMON/HIGGSPEC/SMASS,SCOMP,PMASS,PCOMP,CMASS
      COMMON/SUSYSPEC/MGL,MCHA,U,V,MNEU,NEU
      COMMON/GAUGE/ALSMZ,ALEMMZ,GF,g1,g2,S2TW
      COMMON/SMSPEC/MS,MC,MB,MBP,MT,MTAU,MMUON,MZ,MW
      COMMON/CKM/VUS,VCB,VUB
      COMMON/SFSPEC/MUR,MUL,MDR,MDL,MLR,MLL,MNL,
     . MST1,MST2,MSB1,MSB2,MSL1,MSL2,MSNT,
     . CST,CSB,CSL,MSMU1,MSMU2,MSMUNT,CSMU
      COMMON/RADCOR/RMST1,RMST2,S2T,RMSB1,RMSB2,S2B,XT,XB
      COMMON/RENSCALE/Q2
      COMMON/STSBSCALE/QSTSB
      COMMON/MGUT/MGUT
      COMMON/SUSYCOUP/g1s,g2s,g3s,HTOPS,HBOTS,HTAUS
      COMMON/SUSYMH/MHUS,MHDS,MSS
      COMMON/QMHIGGS/MHUQ,MHDQ,MSQ
      COMMON/QHIGGS/ZHU,ZHD,ZS,H1Q,H2Q,TANBQ
      COMMON/QPAR/LQ,KQ,ALQ,AKQ,MUQ,NUQ
      COMMON/GUTCOUP/G1GUT,G2GUT,G3GUT,LGUT,KGUT,HTOPGUT,
     . HBOTGUT,HTAUGUT
      COMMON/GUTPAR/M1GUT,M2GUT,M3GUT,ALGUT,AKGUT,ATGUT,ABGUT,
     . ATAUGUT,AMUGUT,MHUGUT,MHDGUT,MSGUT,MQ3GUT,MU3GUT,MD3GUT,
     . MQGUT,MUGUT,MDGUT,ML3GUT,ME3GUT,MLGUT,MEGUT
      COMMON/GUTEXT/XIFGUT,XISGUT,MUPGUT,MSPGUT,M3HGUT
      COMMON/SUSYEXT/XIFSUSY,XISSUSY,MUPSUSY,MSPSUSY,M3HSUSY
      COMMON/MICROMG/OMG,OMGMIN,OMGMAX,Xf,sigmaV,xx,dNdx,EMIN,NBIN
      COMMON/MICROMG2/sigmaPiN,sigma0,csPsi,csNsi,csPsd,csNsd
      COMMON/FINETUN/FTSUSY,FTGUT,FTMES
      COMMON/LHCSIG/SIG,SIGT
      COMMON/MCMCPAR/M0CEN,M12CEN,TBCEN,A0CEN,M1CEN,M2CEN,M3CEN,
     . MHDCEN,MHUCEN,LCEN,ALCEN,AKCEN,KCEN,MUCEN,XCEN,XDEV,X,
     . M0DEV,M12DEV,TBDEV,A0DEV,M1DEV,M2DEV,M3DEV,
     . MHDDEV,MHUDEV,LDEV,ALDEV,AKDEV,KDEV,MUDEV,IHIGGS,IGMU
      COMMON/SCANFLAGS/M1FLAG,M2FLAG,M3FLAG,MHDFLAG,MHUFLAG,
     . AKFLAG,ALFLAG
      COMMON/FLAGS/OMGFLAG,MAFLAG
      COMMON/STEPS/NTOT,IDUM

      X=0d0
      XMIN=120d0
      XMAX=128d0
      Y1MIN=1d0
      Y2MIN=1d0

      IF(IFAIL.EQ.9.OR.IFAIL.GE.11)THEN
       X=1d40
      ENDIF

      IF(IFAIL.EQ.1.OR.IFAIL.EQ.3.OR.IFAIL.EQ.5.OR.IFAIL.EQ.7)THEN
       X=X+(2d0-SMASS(1))*1d20
      ENDIF
      IF(IFAIL.EQ.2.OR.IFAIL.EQ.3.OR.IFAIL.EQ.6.OR.IFAIL.EQ.7)THEN
       X=X+(2d0-PMASS(1))*1d20
      ENDIF
      IF(IFAIL.EQ.4.OR.IFAIL.EQ.5.OR.IFAIL.EQ.6.OR.IFAIL.EQ.7)THEN
       X=X+(2d0-CMASS)*1d20
      ENDIF

      IF(IFAIL.EQ.8)THEN
       X=MIN(X,RMST1)
       X=MIN(X,RMSB1)
       X=MIN(X,MST1)
       X=MIN(X,MST2)
       X=MIN(X,MSB1)
       X=MIN(X,MSB2)
       X=MIN(X,MUL)
       X=MIN(X,MUR)
       X=MIN(X,MDL)
       X=MIN(X,MDR)
       X=MIN(X,MSL1)
       X=MIN(X,MSNT)
       X=MIN(X,MSMU1)
       X=MIN(X,MSMUNT)
       X=MIN(X,MLR)
       X=MIN(X,MLL)
       X=MIN(X,MNL)
       X=(1d0-X)*1d20
      ENDIF

      IF(IFAIL.EQ.10)THEN
       DO I=1,NPROB
        IF(I.NE.31)X=X+DABS(PROB(I))
       ENDDO
       X=(1d0+X)*1d10
      ENDIF

      IF(IHIGGS.EQ.1 .OR. IHIGGS.EQ.2)THEN
       IF(SMASS(IHIGGS).LE.XMIN)THEN
        IF(IFAIL.EQ.0)IFAIL=17
        X=X+(2d0-SMASS(IHIGGS)/XMIN)*1d5
       ENDIF
       IF(SMASS(IHIGGS).GE.XMAX)THEN
        IF(IFAIL.EQ.0)IFAIL=17
        X=X+SMASS(IHIGGS)/XMAX*1d5
       ENDIF
       IF(SIG(IHIGGS,10).LE.Y1MIN .AND. SIG(IHIGGS,10).NE.0d0)THEN
        IF(IFAIL.EQ.0)IFAIL=17
        X=X+(2.d0-SIG(IHIGGS,10)/Y1MIN)*1d5
       ENDIF
       IF(SIG(IHIGGS,11).LE.Y2MIN .AND. SIG(IHIGGS,11).NE.0d0)THEN
        IF(IFAIL.EQ.0)IFAIL=17
        X=X+(2.d0-SIG(IHIGGS,11)/Y2MIN)*1d5
       ENDIF
      ENDIF

      IF(FTGUT(NGUT+1).GE.150d0)THEN
       IF(IFAIL.EQ.0)IFAIL=17
        X=X+FTGUT(NGUT+1)/150d0*1d5
      ENDIF

c      X=X+FTGUT(NGUT+1)
      X=X+1d0

c      P=1d0/(1d0+DEXP(DLOG10(X/XCEN)/(.28d0*XDEV)))
      P=1d0/(1d0+DEXP((X-XCEN)/(.28d0*XDEV*MIN(X,XCEN))))
      XDUM=RAN2(IDUM)
c      WRITE(0,10),XCEN,X
c      WRITE(0,10),P,XDUM
c 10   FORMAT(4E16.8)
      IF(P.GE.XDUM)THEN
c       WRITE(0,*)"OK",IFAIL
       XCEN=X
       M0CEN=M0
       M12CEN=M12
       TBCEN=PAR(3)
       A0CEN=A0
       LCEN=PAR(1)
       IF(ALFLAG.EQ.1)THEN
        ALCEN=ALINP
       ENDIF
       IF(AKFLAG.EQ.1)THEN
        AKCEN=AKINP
       ENDIF
       IF(M1FLAG.EQ.1)THEN
        M1CEN=M1INP
       ENDIF
       IF(M2FLAG.EQ.1)THEN
        M2CEN=M2INP
       ENDIF
       IF(M3FLAG.EQ.1)THEN
        M3CEN=M3INP
       ENDIF
       IF(MHDFLAG.EQ.1)THEN
        MHDCEN=MHDINP
       ENDIF
       IF(MHUFLAG.EQ.1)THEN
        MHUCEN=MHUINP
       ENDIF
       IF(MAFLAG.EQ.-5)THEN
        KCEN=PAR(2)
        MUCEN=PAR(4)
       ENDIF
      ELSE
c       WRITE(0,*)"NO",IFAIL
      ENDIF 

      END
